services:
  knowledge-evigraph:
    image: knowledge-evigraph:latest
    build: .
    container_name: knowledge-evigraph
    env_file:
      - .env
    ports:
      - "80:80"
      - "5001:5001"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./.env:/app/.env:ro
